
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.402+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "beneficiaryRegistrationCreateOrUpdateFault", targetNamespace = "http://services.xm.org/xsd")
public class BeneficiaryRegistrationCreateOrUpdateFault extends Exception {
    
    private org.xm.services.xsd.BeneficiaryRegistrationCreateOrUpdateFault beneficiaryRegistrationCreateOrUpdateFault;

    public BeneficiaryRegistrationCreateOrUpdateFault() {
        super();
    }
    
    public BeneficiaryRegistrationCreateOrUpdateFault(String message) {
        super(message);
    }
    
    public BeneficiaryRegistrationCreateOrUpdateFault(String message, Throwable cause) {
        super(message, cause);
    }

    public BeneficiaryRegistrationCreateOrUpdateFault(String message, org.xm.services.xsd.BeneficiaryRegistrationCreateOrUpdateFault beneficiaryRegistrationCreateOrUpdateFault) {
        super(message);
        this.beneficiaryRegistrationCreateOrUpdateFault = beneficiaryRegistrationCreateOrUpdateFault;
    }

    public BeneficiaryRegistrationCreateOrUpdateFault(String message, org.xm.services.xsd.BeneficiaryRegistrationCreateOrUpdateFault beneficiaryRegistrationCreateOrUpdateFault, Throwable cause) {
        super(message, cause);
        this.beneficiaryRegistrationCreateOrUpdateFault = beneficiaryRegistrationCreateOrUpdateFault;
    }

    public org.xm.services.xsd.BeneficiaryRegistrationCreateOrUpdateFault getFaultInfo() {
        return this.beneficiaryRegistrationCreateOrUpdateFault;
    }
}
