
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.440+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "confirmXMTxnAmendmentFault", targetNamespace = "http://services.xm.org/xsd")
public class ConfirmXMTxnAmendmentFault extends Exception {
    
    private org.xm.services.xsd.ConfirmXMTxnAmendmentFault confirmXMTxnAmendmentFault;

    public ConfirmXMTxnAmendmentFault() {
        super();
    }
    
    public ConfirmXMTxnAmendmentFault(String message) {
        super(message);
    }
    
    public ConfirmXMTxnAmendmentFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ConfirmXMTxnAmendmentFault(String message, org.xm.services.xsd.ConfirmXMTxnAmendmentFault confirmXMTxnAmendmentFault) {
        super(message);
        this.confirmXMTxnAmendmentFault = confirmXMTxnAmendmentFault;
    }

    public ConfirmXMTxnAmendmentFault(String message, org.xm.services.xsd.ConfirmXMTxnAmendmentFault confirmXMTxnAmendmentFault, Throwable cause) {
        super(message, cause);
        this.confirmXMTxnAmendmentFault = confirmXMTxnAmendmentFault;
    }

    public org.xm.services.xsd.ConfirmXMTxnAmendmentFault getFaultInfo() {
        return this.confirmXMTxnAmendmentFault;
    }
}
