
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.319+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "confirmAllOutstandingReceiveTxnFault", targetNamespace = "http://services.xm.org/xsd")
public class ConfirmAllOutstandingReceiveTxnFault extends Exception {
    
    private org.xm.services.xsd.ConfirmAllOutstandingReceiveTxnFault confirmAllOutstandingReceiveTxnFault;

    public ConfirmAllOutstandingReceiveTxnFault() {
        super();
    }
    
    public ConfirmAllOutstandingReceiveTxnFault(String message) {
        super(message);
    }
    
    public ConfirmAllOutstandingReceiveTxnFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ConfirmAllOutstandingReceiveTxnFault(String message, org.xm.services.xsd.ConfirmAllOutstandingReceiveTxnFault confirmAllOutstandingReceiveTxnFault) {
        super(message);
        this.confirmAllOutstandingReceiveTxnFault = confirmAllOutstandingReceiveTxnFault;
    }

    public ConfirmAllOutstandingReceiveTxnFault(String message, org.xm.services.xsd.ConfirmAllOutstandingReceiveTxnFault confirmAllOutstandingReceiveTxnFault, Throwable cause) {
        super(message, cause);
        this.confirmAllOutstandingReceiveTxnFault = confirmAllOutstandingReceiveTxnFault;
    }

    public org.xm.services.xsd.ConfirmAllOutstandingReceiveTxnFault getFaultInfo() {
        return this.confirmAllOutstandingReceiveTxnFault;
    }
}
