
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.414+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "confirmXMTransactionFault", targetNamespace = "http://services.xm.org/xsd")
public class ConfirmXMTransactionFault extends Exception {
    
    private org.xm.services.xsd.ConfirmXMTransactionFault confirmXMTransactionFault;

    public ConfirmXMTransactionFault() {
        super();
    }
    
    public ConfirmXMTransactionFault(String message) {
        super(message);
    }
    
    public ConfirmXMTransactionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ConfirmXMTransactionFault(String message, org.xm.services.xsd.ConfirmXMTransactionFault confirmXMTransactionFault) {
        super(message);
        this.confirmXMTransactionFault = confirmXMTransactionFault;
    }

    public ConfirmXMTransactionFault(String message, org.xm.services.xsd.ConfirmXMTransactionFault confirmXMTransactionFault, Throwable cause) {
        super(message, cause);
        this.confirmXMTransactionFault = confirmXMTransactionFault;
    }

    public org.xm.services.xsd.ConfirmXMTransactionFault getFaultInfo() {
        return this.confirmXMTransactionFault;
    }
}
