
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.457+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "createXMTransactionFault", targetNamespace = "http://services.xm.org/xsd")
public class CreateXMTransactionFault extends Exception {
    
    private org.xm.services.xsd.CreateXMTransactionFault createXMTransactionFault;

    public CreateXMTransactionFault() {
        super();
    }
    
    public CreateXMTransactionFault(String message) {
        super(message);
    }
    
    public CreateXMTransactionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CreateXMTransactionFault(String message, org.xm.services.xsd.CreateXMTransactionFault createXMTransactionFault) {
        super(message);
        this.createXMTransactionFault = createXMTransactionFault;
    }

    public CreateXMTransactionFault(String message, org.xm.services.xsd.CreateXMTransactionFault createXMTransactionFault, Throwable cause) {
        super(message, cause);
        this.createXMTransactionFault = createXMTransactionFault;
    }

    public org.xm.services.xsd.CreateXMTransactionFault getFaultInfo() {
        return this.createXMTransactionFault;
    }
}
