
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.468+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "customerRegistrationCreateOrUpdateFault", targetNamespace = "http://services.xm.org/xsd")
public class CustomerRegistrationCreateOrUpdateFault extends Exception {
    
    private org.xm.services.xsd.CustomerRegistrationCreateOrUpdateFault customerRegistrationCreateOrUpdateFault;

    public CustomerRegistrationCreateOrUpdateFault() {
        super();
    }
    
    public CustomerRegistrationCreateOrUpdateFault(String message) {
        super(message);
    }
    
    public CustomerRegistrationCreateOrUpdateFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CustomerRegistrationCreateOrUpdateFault(String message, org.xm.services.xsd.CustomerRegistrationCreateOrUpdateFault customerRegistrationCreateOrUpdateFault) {
        super(message);
        this.customerRegistrationCreateOrUpdateFault = customerRegistrationCreateOrUpdateFault;
    }

    public CustomerRegistrationCreateOrUpdateFault(String message, org.xm.services.xsd.CustomerRegistrationCreateOrUpdateFault customerRegistrationCreateOrUpdateFault, Throwable cause) {
        super(message, cause);
        this.customerRegistrationCreateOrUpdateFault = customerRegistrationCreateOrUpdateFault;
    }

    public org.xm.services.xsd.CustomerRegistrationCreateOrUpdateFault getFaultInfo() {
        return this.customerRegistrationCreateOrUpdateFault;
    }
}
