
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.383+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "editXMTransactionFault", targetNamespace = "http://services.xm.org/xsd")
public class EditXMTransactionFault extends Exception {
    
    private org.xm.services.xsd.EditXMTransactionFault editXMTransactionFault;

    public EditXMTransactionFault() {
        super();
    }
    
    public EditXMTransactionFault(String message) {
        super(message);
    }
    
    public EditXMTransactionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public EditXMTransactionFault(String message, org.xm.services.xsd.EditXMTransactionFault editXMTransactionFault) {
        super(message);
        this.editXMTransactionFault = editXMTransactionFault;
    }

    public EditXMTransactionFault(String message, org.xm.services.xsd.EditXMTransactionFault editXMTransactionFault, Throwable cause) {
        super(message, cause);
        this.editXMTransactionFault = editXMTransactionFault;
    }

    public org.xm.services.xsd.EditXMTransactionFault getFaultInfo() {
        return this.editXMTransactionFault;
    }
}
