
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.329+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "getLoyaltyDetailsFault", targetNamespace = "http://services.xm.org/xsd")
public class GetLoyaltyDetailsFault extends Exception {
    
    private org.xm.services.xsd.GetLoyaltyDetailsFault getLoyaltyDetailsFault;

    public GetLoyaltyDetailsFault() {
        super();
    }
    
    public GetLoyaltyDetailsFault(String message) {
        super(message);
    }
    
    public GetLoyaltyDetailsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetLoyaltyDetailsFault(String message, org.xm.services.xsd.GetLoyaltyDetailsFault getLoyaltyDetailsFault) {
        super(message);
        this.getLoyaltyDetailsFault = getLoyaltyDetailsFault;
    }

    public GetLoyaltyDetailsFault(String message, org.xm.services.xsd.GetLoyaltyDetailsFault getLoyaltyDetailsFault, Throwable cause) {
        super(message, cause);
        this.getLoyaltyDetailsFault = getLoyaltyDetailsFault;
    }

    public org.xm.services.xsd.GetLoyaltyDetailsFault getFaultInfo() {
        return this.getLoyaltyDetailsFault;
    }
}
