
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.473+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "getXMReceiveTxnFault", targetNamespace = "http://services.xm.org/xsd")
public class GetXMReceiveTxnFault extends Exception {
    
    private org.xm.services.xsd.GetXMReceiveTxnFault getXMReceiveTxnFault;

    public GetXMReceiveTxnFault() {
        super();
    }
    
    public GetXMReceiveTxnFault(String message) {
        super(message);
    }
    
    public GetXMReceiveTxnFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetXMReceiveTxnFault(String message, org.xm.services.xsd.GetXMReceiveTxnFault getXMReceiveTxnFault) {
        super(message);
        this.getXMReceiveTxnFault = getXMReceiveTxnFault;
    }

    public GetXMReceiveTxnFault(String message, org.xm.services.xsd.GetXMReceiveTxnFault getXMReceiveTxnFault, Throwable cause) {
        super(message, cause);
        this.getXMReceiveTxnFault = getXMReceiveTxnFault;
    }

    public org.xm.services.xsd.GetXMReceiveTxnFault getFaultInfo() {
        return this.getXMReceiveTxnFault;
    }
}
