
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.408+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "getXMXpinEnquiryFault", targetNamespace = "http://services.xm.org/xsd")
public class GetXMXpinEnquiryFault extends Exception {
    
    private org.xm.services.xsd.GetXMXpinEnquiryFault getXMXpinEnquiryFault;

    public GetXMXpinEnquiryFault() {
        super();
    }
    
    public GetXMXpinEnquiryFault(String message) {
        super(message);
    }
    
    public GetXMXpinEnquiryFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetXMXpinEnquiryFault(String message, org.xm.services.xsd.GetXMXpinEnquiryFault getXMXpinEnquiryFault) {
        super(message);
        this.getXMXpinEnquiryFault = getXMXpinEnquiryFault;
    }

    public GetXMXpinEnquiryFault(String message, org.xm.services.xsd.GetXMXpinEnquiryFault getXMXpinEnquiryFault, Throwable cause) {
        super(message, cause);
        this.getXMXpinEnquiryFault = getXMXpinEnquiryFault;
    }

    public org.xm.services.xsd.GetXMXpinEnquiryFault getFaultInfo() {
        return this.getXMXpinEnquiryFault;
    }
}
