
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.446+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "getXMXpinStatusFault", targetNamespace = "http://services.xm.org/xsd")
public class GetXMXpinStatusFault extends Exception {
    
    private org.xm.services.xsd.GetXMXpinStatusFault getXMXpinStatusFault;

    public GetXMXpinStatusFault() {
        super();
    }
    
    public GetXMXpinStatusFault(String message) {
        super(message);
    }
    
    public GetXMXpinStatusFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetXMXpinStatusFault(String message, org.xm.services.xsd.GetXMXpinStatusFault getXMXpinStatusFault) {
        super(message);
        this.getXMXpinStatusFault = getXMXpinStatusFault;
    }

    public GetXMXpinStatusFault(String message, org.xm.services.xsd.GetXMXpinStatusFault getXMXpinStatusFault, Throwable cause) {
        super(message, cause);
        this.getXMXpinStatusFault = getXMXpinStatusFault;
    }

    public org.xm.services.xsd.GetXMXpinStatusFault getFaultInfo() {
        return this.getXMXpinStatusFault;
    }
}
