
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.338+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "getXMSCancelTxnChargesFault", targetNamespace = "http://services.xm.org/xsd")
public class GetXMSCancelTxnChargesFault extends Exception {
    
    private org.xm.services.xsd.GetXMSCancelTxnChargesFault getXMSCancelTxnChargesFault;

    public GetXMSCancelTxnChargesFault() {
        super();
    }
    
    public GetXMSCancelTxnChargesFault(String message) {
        super(message);
    }
    
    public GetXMSCancelTxnChargesFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetXMSCancelTxnChargesFault(String message, org.xm.services.xsd.GetXMSCancelTxnChargesFault getXMSCancelTxnChargesFault) {
        super(message);
        this.getXMSCancelTxnChargesFault = getXMSCancelTxnChargesFault;
    }

    public GetXMSCancelTxnChargesFault(String message, org.xm.services.xsd.GetXMSCancelTxnChargesFault getXMSCancelTxnChargesFault, Throwable cause) {
        super(message, cause);
        this.getXMSCancelTxnChargesFault = getXMSCancelTxnChargesFault;
    }

    public org.xm.services.xsd.GetXMSCancelTxnChargesFault getFaultInfo() {
        return this.getXMSCancelTxnChargesFault;
    }
}
