
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.377+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "getXMRateCalculateDetailsFault", targetNamespace = "http://services.xm.org/xsd")
public class GetXMRateCalculateDetailsFault extends Exception {
    
    private org.xm.services.xsd.GetXMRateCalculateDetailsFault getXMRateCalculateDetailsFault;

    public GetXMRateCalculateDetailsFault() {
        super();
    }
    
    public GetXMRateCalculateDetailsFault(String message) {
        super(message);
    }
    
    public GetXMRateCalculateDetailsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetXMRateCalculateDetailsFault(String message, org.xm.services.xsd.GetXMRateCalculateDetailsFault getXMRateCalculateDetailsFault) {
        super(message);
        this.getXMRateCalculateDetailsFault = getXMRateCalculateDetailsFault;
    }

    public GetXMRateCalculateDetailsFault(String message, org.xm.services.xsd.GetXMRateCalculateDetailsFault getXMRateCalculateDetailsFault, Throwable cause) {
        super(message, cause);
        this.getXMRateCalculateDetailsFault = getXMRateCalculateDetailsFault;
    }

    public org.xm.services.xsd.GetXMRateCalculateDetailsFault getFaultInfo() {
        return this.getXMRateCalculateDetailsFault;
    }
}
