
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.429+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "getXMTxnAmendmentFault", targetNamespace = "http://services.xm.org/xsd")
public class GetXMTxnAmendmentFault extends Exception {
    
    private org.xm.services.xsd.GetXMTxnAmendmentFault getXMTxnAmendmentFault;

    public GetXMTxnAmendmentFault() {
        super();
    }
    
    public GetXMTxnAmendmentFault(String message) {
        super(message);
    }
    
    public GetXMTxnAmendmentFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetXMTxnAmendmentFault(String message, org.xm.services.xsd.GetXMTxnAmendmentFault getXMTxnAmendmentFault) {
        super(message);
        this.getXMTxnAmendmentFault = getXMTxnAmendmentFault;
    }

    public GetXMTxnAmendmentFault(String message, org.xm.services.xsd.GetXMTxnAmendmentFault getXMTxnAmendmentFault, Throwable cause) {
        super(message, cause);
        this.getXMTxnAmendmentFault = getXMTxnAmendmentFault;
    }

    public org.xm.services.xsd.GetXMTxnAmendmentFault getFaultInfo() {
        return this.getXMTxnAmendmentFault;
    }
}
