
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.423+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "publishRateDetailsFault", targetNamespace = "http://services.xm.org/xsd")
public class PublishRateDetailsFault extends Exception {
    
    private org.xm.services.xsd.PublishRateDetailsFault publishRateDetailsFault;

    public PublishRateDetailsFault() {
        super();
    }
    
    public PublishRateDetailsFault(String message) {
        super(message);
    }
    
    public PublishRateDetailsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PublishRateDetailsFault(String message, org.xm.services.xsd.PublishRateDetailsFault publishRateDetailsFault) {
        super(message);
        this.publishRateDetailsFault = publishRateDetailsFault;
    }

    public PublishRateDetailsFault(String message, org.xm.services.xsd.PublishRateDetailsFault publishRateDetailsFault, Throwable cause) {
        super(message, cause);
        this.publishRateDetailsFault = publishRateDetailsFault;
    }

    public org.xm.services.xsd.PublishRateDetailsFault getFaultInfo() {
        return this.publishRateDetailsFault;
    }
}
