
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.353+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "searchBeneficiaryFault", targetNamespace = "http://services.xm.org/xsd")
public class SearchBeneficiaryFault extends Exception {
    
    private org.xm.services.xsd.SearchBeneficiaryFault searchBeneficiaryFault;

    public SearchBeneficiaryFault() {
        super();
    }
    
    public SearchBeneficiaryFault(String message) {
        super(message);
    }
    
    public SearchBeneficiaryFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SearchBeneficiaryFault(String message, org.xm.services.xsd.SearchBeneficiaryFault searchBeneficiaryFault) {
        super(message);
        this.searchBeneficiaryFault = searchBeneficiaryFault;
    }

    public SearchBeneficiaryFault(String message, org.xm.services.xsd.SearchBeneficiaryFault searchBeneficiaryFault, Throwable cause) {
        super(message, cause);
        this.searchBeneficiaryFault = searchBeneficiaryFault;
    }

    public org.xm.services.xsd.SearchBeneficiaryFault getFaultInfo() {
        return this.searchBeneficiaryFault;
    }
}
