
package org.xm.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-07-19T19:26:59.389+05:30
 * Generated source version: 3.1.4
 */

@WebFault(name = "updateXMTxnStatusFault", targetNamespace = "http://services.xm.org/xsd")
public class UpdateXMTxnStatusFault extends Exception {
    
    private org.xm.services.xsd.UpdateXMTxnStatusFault updateXMTxnStatusFault;

    public UpdateXMTxnStatusFault() {
        super();
    }
    
    public UpdateXMTxnStatusFault(String message) {
        super(message);
    }
    
    public UpdateXMTxnStatusFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdateXMTxnStatusFault(String message, org.xm.services.xsd.UpdateXMTxnStatusFault updateXMTxnStatusFault) {
        super(message);
        this.updateXMTxnStatusFault = updateXMTxnStatusFault;
    }

    public UpdateXMTxnStatusFault(String message, org.xm.services.xsd.UpdateXMTxnStatusFault updateXMTxnStatusFault, Throwable cause) {
        super(message, cause);
        this.updateXMTxnStatusFault = updateXMTxnStatusFault;
    }

    public org.xm.services.xsd.UpdateXMTxnStatusFault getFaultInfo() {
        return this.updateXMTxnStatusFault;
    }
}
